# Generated by Django 4.2 on 2024-02-25 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='почта клиента')),
                ('first_name', models.CharField(max_length=50, verbose_name='имя')),
                ('second_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='отчество')),
                ('last_name', models.CharField(max_length=50, verbose_name='фамилия')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='комментарий')),
            ],
            options={
                'verbose_name': 'клиент',
                'verbose_name_plural': 'клиенты',
                'ordering': ('last_name',),
            },
        ),
        migrations.CreateModel(
            name='Letter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_letter', models.CharField(max_length=100, verbose_name='тема письма')),
                ('text_letter', models.TextField(verbose_name='текст письма')),
            ],
            options={
                'verbose_name': 'письмо',
                'verbose_name_plural': 'письма',
                'ordering': ('name_letter',),
            },
        ),
        migrations.CreateModel(
            name='Mail_log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_try', models.DateField(auto_now=True, verbose_name='дата последней попытки')),
                ('status_try', models.BooleanField(verbose_name='статус попытки')),
                ('answer_server', models.CharField(blank=True, max_length=150, null=True, verbose_name='ответ сервера')),
            ],
            options={
                'verbose_name': 'лог',
                'verbose_name_plural': 'логи',
                'ordering': ('last_try', 'status_try'),
            },
        ),
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='без имени', max_length=50, null=True, verbose_name='название рассылки')),
                ('time_to_send', models.TimeField(verbose_name='время рассылки')),
                ('period_start', models.DateField(verbose_name='дата начала рассылки')),
                ('period_fin', models.DateField(verbose_name='дата конца рассылки')),
                ('period', models.CharField(choices=[('раз в день', 'раз в день'), ('раз в неделю', 'раз в неделю'), ('раз в месяц', 'раз в месяц'), ('раз в минуту (на тесты)', 'раз в минуту (на тесты)')], default='раз в минуту (на тесты)', max_length=25, verbose_name='периодичность рассылки')),
                ('status', models.IntegerField(choices=[(0, 'создана'), (1, 'в процессе'), (2, 'завершена')], default=0, verbose_name='статус рассылки')),
            ],
            options={
                'verbose_name': 'рассылка',
                'verbose_name_plural': 'рассылки',
                'ordering': ('status',),
            },
        ),
    ]
