# Generated by Django 4.2 on 2024-02-25 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0003_alter_letter_creator_alter_newsletter_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='second_name',
            field=models.CharField(blank=True, default='-', max_length=50, null=True, verbose_name='отчество'),
        ),
    ]
