# Generated by Django 4.2 on 2024-02-28 10:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('newsletter', '0007_alter_client_creator_alter_letter_creator_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='creator',
            field=models.ForeignKey(auto_created=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='создатель рассылки'),
        ),
    ]
