# Generated by Django 4.2 on 2024-03-06 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0010_alter_newsletter_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='last_try',
            field=models.DateTimeField(blank=True, null=True, verbose_name='дата/время последней отправки'),
        ),
    ]
