# Generated by Django 4.2 on 2024-02-25 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'verbose_name': 'запись', 'verbose_name_plural': 'записи'},
        ),
    ]
