# Generated by Django 4.2 on 2024-02-28 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blog_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ('count_view',), 'verbose_name': 'запись', 'verbose_name_plural': 'записи'},
        ),
    ]
